# Generated by Django 4.2 on 2023-04-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auditcategory_auditmeasure_auditorganization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='action',
            new_name='proposed',
        ),
    ]
