# Generated by Django 4.2 on 2023-04-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_action_violation_proposed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='action',
            new_name='incidentAction',
        ),
    ]
